{
 "title": "MEV-Relayer",
 "description": "Relayer metrics",
 "time": { "from": "2024-08-22T16:33:00.000Z", "to": "2024-08-22T17:00:00.000Z" },
 "panels": [
  {
   "title": "Data collected from beacon node",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Data from Beacon node\n\nFrom a standard lighthouse beacon client, we can collect information like: epoch, headslot, and peer connection on the networking layer."
   }
  },
  { "title": "Vanilla Lighthouse beacon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Peer ID to multiaddress",
   "type": "table",
   "description": "Collect peers and their associated multiaddresses from libp2p layer, extracted from `peer-manager` of `lighthouse_network` crate",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max(libp2p_peer_to_multiaddr) by (multiaddress, peer_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current beacon epoch",
   "type": "stat",
   "description": "Current epoch",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slotclock_present_epoch" }
   ]
  },
  {
   "title": "Current head slot",
   "type": "stat",
   "description": "Latest head slot",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, label_replace(beacon_head_slot{job=~\"cl-[0-9]+-lighthouse-geth\"}, \"index\", \"$1\", \"job\", \"cl-([0-9]+)-lighthouse-geth\"))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Modified \"Metaclear\" Lighhouse beacon",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true
  },
  {
   "title": "Knowing validators' public keys and IP addresses",
   "type": "text",
   "description": "Table on the right shows the association of validators' public key and IP addresses. This data can be obtained by running a CL.",
   "gridPos": { "h": 22, "w": 4, "x": 0, "y": 13 },
   "options": {
    "content": "<div>Previously, HOPR team conducted research on <b>“validator sniping”</b>, \na technique where attackers exploit the Proof-of-Stake (PoS) protocol to steal block rewards from validators. </div>\n\n<br>\n<div>This attack takes advantage of the fact that <b>both validators' public keys and IP addresses are publicly known</b>.</div>\n\n<br>\n<div>You can read more about our findings in our blog post: <a href=\"https://medium.com/hoprnet/proof-of-stake-validator-sniping-research-8670c4a88a1c\">\"Proof-of-Stake Validator Sniping Research\"</a>.</div>\n\n<br>\n<center><img src=\"https://i.imgur.com/YQSyTBH.png\" width=\"150\" height=\"150\"/></center>\n\n<br>\n<div><i>Source: https://medium.com/hoprnet/proof-of-stake-validator-sniping-research-8670c4a88a1c</i></div>"
   }
  },
  {
   "title": "Peer ID and pubkey from attestations",
   "type": "table",
   "description": "Associating validators' public keys with peer IDs by observing attestations.",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 13 },
   "targets": [
    {
     "expr": "sum(peer_id_to_pubkey) by (peer_id, pubkey)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(peer_id_to_pubkey) by (pubkey)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "From pubkey to CL multiaddress",
   "type": "table",
   "description": "By observing as many attestations as possible, the node can reliably associate a public key with its multiaddress. Below is the most likely association.",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "topk(1, sum(peer_id_to_pubkey) by (peer_id, pubkey)) by (pubkey)",
     "legendFormat": "__auto"
    },
    { "expr": "libp2p_peer_to_multiaddr", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Modified \"Metaclear\" relayer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "\"Meta-clear\" MEV Relay",
   "type": "text",
   "description": "The modified `flashbot/mev-relay` implementation extracts metadata of http requests sent to the relayer.",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 36 },
   "options": {
    "content": "<h1>\"Meta-clear\" MEV Relay</h1>\n\n<div>The modified `flashbot/mev-relay` implementation extracts metadata of http requests sent to the relayer, particularly on the following endpoints:</div>\n<br>\n\n<div>On the <u>validators</u> side:</div>\n<ul>\n  <li><b>POST</b> /eth/v1/builder/blinded_blocks</li>\n  <li><b>GET</b> /eth/v1/builder/header/{slot}/{parent_hash}/{pubkey}</li>\n  <li><b>POST</b> /eth/v1/builder/validators</li>\n</ul>\n\n<div>On the <u>block builders</u> side:</div>\n<ul>\n  <li><b>POST</b> /relay/v1/builder/blocks</li>\n  <li><b>GET</b>  /relay/v1/builder/validators</li>\n</ul>"
   }
  },
  {
   "title": "MEV-Relayer http endpoint requests [per min]",
   "type": "timeseries",
   "description": "Number of http requests per mev-relayer endpoint",
   "gridPos": { "h": 14, "w": 15, "x": 9, "y": 36 },
   "targets": [
    {
     "expr": "rate(relayer_http_requests_total[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Registered validators",
   "type": "table",
   "description": "All the validators registered to the current mev-relayer",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT pubkey, CONCAT(ip, ':', port) AS mev_boost_ip, validators.inserted_at as registration_timestamp FROM custom_validator_registration validators\nLEFT JOIN\ncustom_metadata metadata\nON metadata.key=validators.pubkey"
    },
    {
     "expr": "topk(1, sum(peer_id_to_pubkey) by (peer_id, pubkey)) by (pubkey)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of slots containing blocks proposed by block builders via MEV-Relay per minute",
   "type": "timeseries",
   "description": "Number of slots containing blocks proposed by block builders via MEV-Relay per minute",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "-- SELECT slot, date_trunc('minute', inserted_at) as timestamp_in_minute\nSELECT count(slot), date_trunc('minute', inserted_at) as timestamp_in_minute\nFROM custom_payload_delivered\nGROUP BY timestamp_in_minute\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Slot Processing",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_block_production_slot_process_seconds_sum[1m])\n/\nrate(beacon_block_production_slot_process_seconds_count[1m])"
    }
   ]
  },
  { "title": "Attacking next epoch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Proposer of the current and next epoches",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "rawSql": "SELECT slot, (slot/32 + 1) as epoch, validator_index, proposer_pubkey FROM custom_proposer_duties \nORDER BY slot DESC\nLIMIT 64"
    }
   ]
  },
  {
   "title": "Who to attack in the next 12ish min",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "rawSql": "WITH validator_metadata AS (\n  SELECT pubkey, CONCAT(ip, ':', port) AS mev_boost_ip, metadata.inserted_at AS request_timestamp FROM custom_validator_registration validators\n  LEFT JOIN\n  custom_metadata metadata\n  ON metadata.key=validators.pubkey\n), next_epoch_proposers AS (\n  SELECT slot, slot/32 as epoch, validator_index, proposer_pubkey FROM custom_proposer_duties \n  ORDER BY slot DESC\n  LIMIT 32\n)\n\nSELECT slot, epoch, validator_index, proposer_pubkey, mev_boost_ip FROM next_epoch_proposers\nLEFT JOIN validator_metadata\nON validator_metadata.pubkey = next_epoch_proposers.proposer_pubkey"
    }
   ]
  },
  {
   "title": "RANDAO values",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "rawSql": "SELECT slot, prev_randao, parent_hash, inserted_at FROM custom_payload_attributes\nORDER BY slot DESC\nLIMIT 50 "
    }
   ]
  },
  {
   "title": "Distribution of starting time and duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 }
  },
  {
   "title": "Time that block builders submit blocks to the relayer compared with the start of a slot",
   "type": "histogram",
   "description": "Start time of processing submit block request.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "relayer_submit_block_start_time_into_slot",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration of block builders submit blocks to the relayer",
   "type": "histogram",
   "description": "Time to take to process the block submission request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    { "expr": "relayer_submit_block_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time that validators get header of a slot from the relayer compared with the start of a slot",
   "type": "histogram",
   "description": "Start time of getting slot header request.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "relayer_get_header_start_time_into_slot",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration of validators get headers from the relayer",
   "type": "histogram",
   "description": "Time to take for get header request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "targets": [
    { "expr": "relayer_get_header_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time that validators get payload of a slot from the relayer compared with the start of a slot",
   "type": "histogram",
   "description": "Start time of getting payload request.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "relayer_get_payload_start_time_into_slot",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration of validators get payloads from the relayer",
   "type": "histogram",
   "description": "Time to take for get payloads request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "targets": [
    { "expr": "relayer_get_payload_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time that the relayer publish the block for a slot from the relayer compared with the start of a slot",
   "type": "histogram",
   "description": "Start time of publishing a block",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "relayer_publish_block_start_time_into_slot",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration of relayers publish a block via its beacon node",
   "type": "histogram",
   "description": "Time for relayers to publish a block via its local beacon node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "targets": [
    {
     "expr": "relayer_beacon_elapsed_time_histogram{endpoint=\"publish_duration\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}